services:
  - type: web
    name: visionparse
    env: python
    region: oregon
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn visionparse_admin.wsgi:application
    preDeployCommand: |
      python manage.py collectstatic --noinput
      python manage.py migrate
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: visionparse_admin.settings
      - key: PYTHON_VERSION
        value: 3.11.9