# Generated by Django 5.2.4 on 2025-07-15 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parser', '0002_documentbatch_userdocument_delete_document_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentbatch',
            name='custom_fields',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='documentbatch',
            name='strict_mode',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='documentbatch',
            name='result_format',
            field=models.CharField(choices=[('csv', 'CSV'), ('xlsx', 'XLSX')], max_length=10),
        ),
    ]
