# Generated by Django 3.1.12 on 2025-07-16 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parser', '0004_alter_documentbatch_result_format'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdocument',
            name='user',
        ),
        migrations.DeleteModel(
            name='DocumentBatch',
        ),
        migrations.DeleteModel(
            name='UserDocument',
        ),
    ]
